- name: configure nodejs
  include_role:
    name: common
    tasks_from: nodejs.yaml

- name: configure app_setup
  include_role:
    name: common
    tasks_from: app_setup.yaml

- name: configure systemd_setup
  include_role:
    name: common
    tasks_from: systemd_setup.yaml

- name: copy mongodb repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: install mongodb client
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: present

- name: check products loaded or not
  ansible.builtin.command: mongosh --host mongodb.dsops84.space --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
  register: catalogue_output

- name: print catalogue output
  ansible.builtin.debug:
    msg: "{{ catalogue_output }}"

- name: load products
  ansible.builtin.shell: mongosh --host mongodb.dsops84.space < /app/db/master-data.js
  when: catalogue_output.stdout | int < 0