- name: create app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Add application User
  ansible.builtin.user:
    name: roboshop
    shell: /sbin/nologin
    system: true
    home: /app

- name: Unarchive a file that needs to be downloaded
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip # downloand and unarchive
    dest: /app
    remote_src: yes