- name: disabling nodejs
  ansible.builtin.command: dnf module disable nodejs -y

- name: enabling nodejs
  ansible.builtin.command: dnf module enable nodejs:20 -y
  register: command_output

- name: installing nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: present

- name: Update packages based on package.json to their latest version.
  community.general.npm:
    path: /app
    state: present