- name: Copying catalogue.service
  ansible.builtin.template:
    src: catalogue.service.j2
    dest: /etc/systemd/system/catalogue.service

- name: systemctl deamon reload
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: start and enable catalogue
  ansible.builtin.service:
    name: catalogue
    state: started
    enabled: yes